"""add unique constraint on approval_votes (request_id, approver_id)

Revision ID: 1a87a657bb74
Revises: e51b95e5c46b
Create Date: 2026-04-13 12:48:59.459485

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a87a657bb74"
down_revision: str | None = "e51b95e5c46b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval_votes", schema=None) as batch_op:
        batch_op.create_index("uq_vote_request_approver", ["request_id", "approver_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approval_votes", schema=None) as batch_op:
        batch_op.drop_index("uq_vote_request_approver")

    # ### end Alembic commands ###
