"""doctrine_outbox_calibration_snapshots

Revision ID: 4dca71e6e14e
Revises: f6fff83cbb5c
Create Date: 2026-04-13 10:15:50.561261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dca71e6e14e'
down_revision: Union[str, None] = 'f6fff83cbb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('ece', sa.Float(), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('needs_recalibration', sa.Boolean(), nullable=False),
    sa.Column('per_node_ece', sa.JSON(), nullable=True),
    sa.Column('bins', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_snapshots_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('doctrine_outbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_type', sa.String(length=64), nullable=False),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctrine_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctrine_outbox_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index('ix_doctrine_outbox_status_next', ['status', 'next_retry_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctrine_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_doctrine_outbox_status_next')
        batch_op.drop_index(batch_op.f('ix_doctrine_outbox_batch_id'))

    op.drop_table('doctrine_outbox')
    with op.batch_alter_table('calibration_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_snapshots_recorded_at'))

    op.drop_table('calibration_snapshots')
    # ### end Alembic commands ###
