"""Initial schema: traces, critic_registry, policies, approvals, labeling_queue

Revision ID: 5bae08f562c8
Revises: 
Create Date: 2026-04-11 12:38:49.800189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bae08f562c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('required_approvals', sa.String(), nullable=False),
    sa.Column('received_approvals', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capability_token', sa.Text(), nullable=True),
    sa.Column('token_scope', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_approval_status', ['status'], unique=False)
        batch_op.create_index('ix_approval_trace', ['trace_id'], unique=False)

    op.create_table('approval_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_votes_request_id'), ['request_id'], unique=False)

    op.create_table('critic_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('lora_adapter_path', sa.String(), nullable=True),
    sa.Column('lora_adapter_version', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('threshold_pass', sa.Float(), nullable=False),
    sa.Column('threshold_halt', sa.Float(), nullable=False),
    sa.Column('can_halt', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('critic_registry', schema=None) as batch_op:
        batch_op.create_index('ix_critic_active', ['is_active'], unique=False)
        batch_op.create_index('ix_critic_type', ['node_type'], unique=False)

    op.create_table('labeling_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('source_node', sa.String(), nullable=False),
    sa.Column('failure_type', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('critic_output', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('corrected_response', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('training_batch_id', sa.String(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('labeled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labeling_queue', schema=None) as batch_op:
        batch_op.create_index('ix_label_failure_type', ['failure_type'], unique=False)
        batch_op.create_index('ix_label_source', ['source_node'], unique=False)
        batch_op.create_index('ix_label_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_labeling_queue_trace_id'), ['trace_id'], unique=False)

    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_pattern', sa.String(), nullable=False),
    sa.Column('resource_pattern', sa.String(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('required_approvals', sa.String(), nullable=False),
    sa.Column('max_executions_per_hour', sa.String(), nullable=True),
    sa.Column('allowed_parameters', sa.JSON(), nullable=True),
    sa.Column('blocked_parameters', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.create_index('ix_policy_active', ['is_active'], unique=False)
        batch_op.create_index('ix_policy_decision', ['decision'], unique=False)

    op.create_table('traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('immune_verdict', sa.String(length=20), nullable=False),
    sa.Column('immune_score', sa.Float(), nullable=True),
    sa.Column('immune_details', sa.JSON(), nullable=True),
    sa.Column('asflc_result', sa.JSON(), nullable=True),
    sa.Column('asflc_chosen_path', sa.String(), nullable=True),
    sa.Column('asflc_confidence', sa.Float(), nullable=True),
    sa.Column('asflc_loops', sa.Integer(), nullable=True),
    sa.Column('critic_verdict', sa.String(length=20), nullable=True),
    sa.Column('critic_scores', sa.JSON(), nullable=True),
    sa.Column('critic_rollback_count', sa.Integer(), nullable=True),
    sa.Column('governance_status', sa.String(length=20), nullable=True),
    sa.Column('governance_policy_id', sa.String(), nullable=True),
    sa.Column('governance_token_id', sa.String(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('output_scan_verdict', sa.String(length=20), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('trace_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index('ix_trace_created', ['created_at'], unique=False)
        batch_op.create_index('ix_trace_session_seq', ['session_id', 'sequence'], unique=False)
        batch_op.create_index('ix_trace_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_session_id'))
        batch_op.drop_index('ix_trace_status')
        batch_op.drop_index('ix_trace_session_seq')
        batch_op.drop_index('ix_trace_created')

    op.drop_table('traces')
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_decision')
        batch_op.drop_index('ix_policy_active')

    op.drop_table('policies')
    with op.batch_alter_table('labeling_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labeling_queue_trace_id'))
        batch_op.drop_index('ix_label_status')
        batch_op.drop_index('ix_label_source')
        batch_op.drop_index('ix_label_failure_type')

    op.drop_table('labeling_queue')
    with op.batch_alter_table('critic_registry', schema=None) as batch_op:
        batch_op.drop_index('ix_critic_type')
        batch_op.drop_index('ix_critic_active')

    op.drop_table('critic_registry')
    with op.batch_alter_table('approval_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_votes_request_id'))

    op.drop_table('approval_votes')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_trace')
        batch_op.drop_index('ix_approval_status')
        batch_op.drop_index(batch_op.f('ix_approval_requests_trace_id'))

    op.drop_table('approval_requests')
    # ### end Alembic commands ###
