"""add beliefs table for Phase 12 memory system

Revision ID: 8a4579763b4d
Revises: a7bfd492ce12
Create Date: 2026-04-17 14:33:12.237046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4579763b4d'
down_revision: Union[str, None] = 'a7bfd492ce12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beliefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity', sa.String(length=200), nullable=False),
    sa.Column('predicate', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_alpha', sa.Float(), nullable=False),
    sa.Column('confidence_beta', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_trace_id', sa.String(), nullable=True),
    sa.Column('extractor_version', sa.String(length=60), nullable=True),
    sa.Column('derived_from', sa.JSON(), nullable=True),
    sa.Column('contradicts', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=True),
    sa.Column('agent_id', sa.String(length=120), nullable=True),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('belief_hash', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beliefs', schema=None) as batch_op:
        batch_op.create_index('ix_belief_entity_predicate_current', ['entity', 'predicate', 'superseded_at'], unique=False)
        batch_op.create_index('ix_belief_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_belief_observed_at', ['observed_at'], unique=False)
        batch_op.create_index('ix_belief_user_scope', ['user_id', 'session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beliefs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beliefs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beliefs_source_trace_id'), ['source_trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_beliefs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beliefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beliefs_user_id'))
        batch_op.drop_index(batch_op.f('ix_beliefs_source_trace_id'))
        batch_op.drop_index(batch_op.f('ix_beliefs_session_id'))
        batch_op.drop_index(batch_op.f('ix_beliefs_agent_id'))
        batch_op.drop_index('ix_belief_user_scope')
        batch_op.drop_index('ix_belief_observed_at')
        batch_op.drop_index('ix_belief_entity_type')
        batch_op.drop_index('ix_belief_entity_predicate_current')

    op.drop_table('beliefs')
    # ### end Alembic commands ###
