"""make prompt_template nullable

Revision ID: f6fff83cbb5c
Revises: 5bae08f562c8
Create Date: 2026-04-11 13:57:44.896463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fff83cbb5c'
down_revision: Union[str, None] = '5bae08f562c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critic_registry', schema=None) as batch_op:
        batch_op.alter_column('prompt_template',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('critic_registry', schema=None) as batch_op:
        batch_op.alter_column('prompt_template',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
